---
title: "Report_WP2_multiorganism"
format: html
editor: visual
---

```{r set-up}
library(data.table)
library(flextable)
library(ggpubr)
library(targets)

source('_targets.R')
```

## General information

```{r set-up}
tar_load(allvars_merged)
allvars_merged$dt_summarized[, list(total_sites=uniqueN(site), 
                                    pr=.SD[stream_type=='PR', uniqueN(site)],
                                    npr=.SD[stream_type=='TR', uniqueN(site)]), 
                             by=country]

tar_load(env_dt)
check <- env_dt[, .N, by=.(site, state_of_flow)] %>% 
  dcast(site~state_of_flow) %>%
  .[, total_n := sum(c(`F`, D, IP), na.rm=T), by=site]
check
```

```{r mod tabl}
#Check unique miv taxa
tar_load(bio_dt)
check <- melt(bio_dt$miv, id.vars = intersect(metacols, names(bio_dt$miv)))[, unique(variable)] %>%
    .[grepl('gen.', .)] %>%
  as.character


#Check unique diatom taxa
check_dia <- melt(bio_dt$dia_sedi, 
              id.vars = intersect(metacols, names(bio_dt$dia_sedi))) %>%
  rbind(melt(bio_dt$dia_biof, 
              id.vars = intersect(metacols, names(bio_dt$dia_biof))),
        use.bames=T, fill=T) %>%
  .[value>0,] %>%
  .[!duplicated(variable),]
check_dia[value>0,length(unique(gsub(' ', '_', variable)))]

#Check unique fungi taxa
check_fun <- melt(bio_dt$fun_sedi, 
              id.vars = intersect(metacols, names(bio_dt$fun_sedi))) %>%
  rbind(melt(bio_dt$fun_biof, 
              id.vars = intersect(metacols, names(bio_dt$fun_biof))),
        use.bames=T, fill=T) %>%
  .[value>0,] %>%
  .[!duplicated(variable),]
check_fun[value>0,length(unique(gsub(' ', '_', variable)))]

#Check unique bacteria taxa
check_bac <- melt(bio_dt$bac_sedi, 
              id.vars = intersect(metacols, names(bio_dt$bac_sedi))) %>%
  rbind(melt(bio_dt$bac_biof, 
              id.vars = intersect(metacols, names(bio_dt$bac_biof))),
        use.bames=T, fill=T) %>%
  .[value>0,] %>%
  .[!duplicated(variable),]
check_bac[value>0,length(unique(gsub(' ', '_', variable)))]

check_cor_div_habvol()#Check range of intermittence in the Albarine
tar_load(allvars_summarized)
check_fr <- allvars_summarized$dt[!duplicated(site) & country == 'France',
                                     .(DurD_samp, stream_type)]
allvars_summarized$dt[!duplicated(site), .N, 
                         by=.(stream_type, country)]

```

```{r hydrowindow_stats}
tar_load(summary_multiorganism_richness)

summary_multiorganism_richness$dt[, .SD[test_parabolic==T, .N]/.N, by=organism]


tar_load(biof_vs_sedi_emtrends_rma_table)
biof_vs_sedi_emtrends_rma_table$dt[, .SD[pval>0.05 | I2 > 0.25, .N]/.SD[,.N]]
```



```{r site_gamma}
tar_load(allvars_summarized)
richness_stats <- rbind(
  allvars_summarized$dt[, list(mean_richness_avg = mean(mean_richness),
                               mean_richness_sd = sd(mean_richness)), 
                        by=.(country, organism)],
  allvars_summarized$dt[, list(country='All',
                               mean_richness_avg=mean(mean_richness),
                               mean_richness_sd=sd(mean_richness)),
                        by=organism]
)

ggplot(richness_stats, aes(x=country, y=mean_richness_avg, fill=country)) +
  geom_bar(stat='identity') +
  facet_wrap(~organism, scale='free')

richness_stats

```

```{r maps}
in_ssn_summarized <- tar_read(ssn_eu_summarized)

map_durdsamp <- map_ssn_facets(in_ssn = in_ssn_summarized[[1]]$ssn, 
               in_pts = 'obs',
               ptcolor_col = "DurD_samp", 
               facet_col = 'country',
               linewidth_col = 'qsim_avg',
               linecolor_col = "DurD_samp",
               page_title = "Proportion of zero-flow days over sampling period",
               shape_col = 'stream_type',
               nbreaks = 10,
               cover_zero = TRUE
)
ggsave(file.path(figdir, 'map_DurD_samp.pdf'),
       map_durdsamp, height = 12, width=8)
```

```{r export all mean annual richness model tables}
ssn_mods_yr_table_list <- list(
  miv_richness = tar_read(ssn_mods_miv_richness_yr)$model_selection_table,
  miv_invsimpson = tar_read(ssn_mods_miv_invsimpson_yr)$model_selection_table,
  ept_richness = tar_read(ssn_mods_ept_richness_yr)$model_selection_table,
  och_richness = tar_read(ssn_mods_och_richness_yr)$model_selection_table,
  dia_sedi_richness = tar_read(ssn_mods_dia_sedi_richness_yr)$model_selection_table,
  dia_sedi_invsimpson = tar_read(ssn_mods_dia_sedi_invsimpson_yr)$model_selection_table,
  dia_biof_richness = tar_read(ssn_mods_dia_biof_richness_yr)$model_selection_table,
  dia_biof_invsimpson = tar_read(ssn_mods_dia_biof_invsimpson_yr)$model_selection_table,
  fun_sedi_richness = tar_read(ssn_mods_fun_sedi_richness_yr)$model_selection_table,
  fun_sedi_invsimpson = tar_read(ssn_mods_fun_sedi_invsimpson_yr)$model_selection_table,
  fun_biof_richness = tar_read(ssn_mods_fun_biof_richness_yr)$model_selection_table,
  fun_biof_invsimpson = tar_read(ssn_mods_fun_biof_invsimpson_yr)$model_selection_table,
  bac_sedi_richness = tar_read(ssn_mods_bac_sedi_richness_yr)$model_selection_table,
  bac_sedi_invsimpson = tar_read(ssn_mods_bac_sedi_invsimpson_yr)$model_selection_table,
  bac_biof_richness = tar_read(ssn_mods_bac_biof_richness_yr)$model_selection_table,
  bac_biof_invsimpson = tar_read(ssn_mods_bac_biof_invsimpson_yr)$model_selection_table
) 

organism_col <- as.data.table(lapply(ssn_mods_yr_table_list, nrow)) %>%
  data.table::melt(variable.name='organism_var') %>%
  .[, list(organism_var=rep(organism_var, value))]

family_dt <- lapply(tar_read(ssn_mod_yr_fit_multiorganism), function(x) {
  call <- x$call
  if ('family'  %in% names(call)) {
    call$family
  } else {
    'Gaussian'
  }
}) %>% as.matrix(family) %>%
  as.data.table(keep.rownames=T) %>%
  setnames(c('organism_var', 'family'))

ssn_mods_yr_dt_merged <- lapply(ssn_mods_yr_table_list, 
                             function(x) as.data.table(x, keep.rownames=T)) %>%
  rbindlist(fill=T, use.names=T) %>%
  cbind(organism_col, .) %>%
  merge(family_dt, by='organism_var')

fwrite(ssn_mods_yr_dt_merged,
       file.path(figdir, 
                 paste0('multiorganism_yr_model_selection_tables_',
                        format(Sys.Date(), '%Y%m%d'), '.csv'))
)



```

```{r count variables}
setdiff(hydrowindow_varcomp_richness_miv_nopools$dt[, unique(hydro_var)],
        'null')

setdiff(allvars_summarized$cols$hydro_con_summarized,
        c('qsim_avg_samp', 'DurD_yr', 'DurD_avg_samp'))


```

```{r summarized model table and plots}
tar_load(ssn_mod_yr_perf_multiorganism)

fwrite(ssn_mod_yr_perf_multiorganism,
       file.path(figdir, 'ssn_mod_yr_perf_multiorganism_richness.csv'))

tar_load(ssn_proj_plots)
fwrite(ssn_proj_plots$summarized_reldiff_stats_dt,
       file.path(figdir, 'ssn_proj_mean_reldiff_stats.csv'))
fwrite(ssn_proj_plots$all_reldiff_stats_dt,
       file.path(figdir, 'ssn_proj_all_reldiff_stats.csv'))

fwrite(ssn_proj_plots$summarized_absdiff_stats_dt,
       file.path(figdir, 'ssn_proj_mean_absdiff_stats.csv'))
fwrite(ssn_proj_plots$all_absdiff_stats_dt,
       file.path(figdir, 'ssn_proj_all_absdiff_stats.csv'))

check_organism <- ssn_proj_plots$all_reldiff_stats_dt[
  variable=='div_change_late', 
  mean(mean_change), by=.(scenario, country, organism)] %>%
  .[, mean_mean_change := mean(V1), by=.(scenario, organism)]


names(ssn_proj_plots$summarized_reldiff_stats_dt)

pr_tr_cast <- data.table::melt(ssn_proj_plots$summarized_reldiff_stats_dt, 
                   id.vars=c('organism', 'scenario', 'stream_type')) %>%
  .[variable != 'country_mean_change',] %>%
  data.table::dcast(organism+scenario+variable~stream_type) %>%
  .[, abs_diff := abs(TR)>=abs(PR)]


pr_tr_ratio <- pr_tr_cast[, type_ratio := TR/PR] %>%
  .[, list(mean_ratio = mean(type_ratio)), by=.(organism, scenario)]

#Cross-DRN average difference in absolute richness loss between NPR and PR
pr_tr_abs_cast <- ssn_proj_plots$all_absdiff_stats_dt[
  variable=='div_change_abs_late'
  , mean(mean_change),
  by=.(organism, scenario, stream_type, country)] %>%
  data.table::dcast(organism+scenario+country~stream_type) 

pr_tr_abs_diff <- pr_tr_abs_cast[, type_diff := TR-PR] %>%
  .[, list(mean_diff = mean(type_diff)), by=.(organism, scenario)]

#Average and maximum loss across all sites
ssn_proj_plots$all_absdiff_stats_dt[
  variable=='div_change_abs_late', 
  list(mean_absdiff=mean(mean_change),
       max_absdiff=max(mean_change),
       min_absdiff=min(mean_change)
  ),
  by=.(organism, scenario)]

ssn_proj_plots$all_absdiff_stats_dt[
  variable=='div_change_abs_late' & organism=='miv_nopools' & scenario=='ssp585',
  .SD[mean_change < -5,.N]/.N] 


ssn_proj_plots$all_absdiff_stats_dt[variable=='div_change_abs_late', 
                 mean(mean_change),
                 ]

```
