pkg_vec <- list(
  'dbscan',
  'dplyr',
  'ggnewscale',
  'ggnetwork',
  'ggplot2',
  'gridExtra',
  'lmerTest', 
  'lme4', 
  'lubridate',
  'lwgeom',
  'magrittr',
  'MuMIn', 
  'ncdf4',
  'plotly',
  'qs',
  'readxl',
  'reshape2',
  'rlang',
  'rprojroot',
  'sf',
  'sfnetworks',
  'skimr',
  'SSN2',
  'SSNbler',
  'stringr',
  'tarchetypes',
  'targets',
  'terra',
  'tibble',
  'tidygraph',
  'tidyterra',
  'tidytext',
  'vegan',
  'mapview',
  'data.table')
lapply(pkg_vec, function(p) {
  suppressWarnings(
    suppressPackageStartupMessages(
      library(p, character.only = TRUE, warn.conflicts = FALSE, quietly = FALSE)
    ))
})
